### ISSUE TITLE
"EASE Songmaker Software" from Roland not working with SoftMPU

### ISSUE THREAD

**Issue by Knimrod** [bjt42/softmpu#23]
I'm not sure if this project is still active but I perceive this as a possible bug to consider:  "Ease Songmaker Software" was included with a package that included the MPU-401 (MPU-IPC) and the MT-32 from Roland in 1988.  Roland EASE is a MIDI music editor and playback program designed specifically for the Roland MT32. It supports a variety of effects, and editing features.  As installed on my computer (MISTer), the EASE software will load and modify its song files but refuses to play them.  Ease thinks its playing the file (it says "Playing") but it appears to be stuck waiting for a cue from the MPU-401 as the note counter displayed in Ease does not increment.  I think Ease is otherwise working properly as it does seem to generate various MIDI actions; Starting song playback, stopping song playback, and generate MIDI events as seen on status LEDs on the USB-MIDI adapter  I'm using (Roland UM-1ex).  I'm using SoftMPU with a MISTer fpga for which most any other MIDI application I tried, works nominally.  My understanding is that in intelligent mode, the MPU-401 has an onboard hardware timer that can be used to determine when to output MIDI events for sequenced playback.  Is this feature incorporated in SoftMPU?

**Comment by bjt42** [comment]
This software may require the metronome function of the MPU-401, which is not supported by SoftMPU because it's not required by game software.
