### ISSUE TITLE
SOFTMPU and DOS4/GW games 

### ISSUE THREAD

**Issue by alessioscand** [bjt42/softmpu#26]
Hello and **thank you** so much for SOFTMPU, I use it in conjunction with the MT32-PI project by connecting the GPIO to the COM port of old PCs, ThinClients and even FPGA (MiST) and everything works perfectly.

In addition to the Roland MT-32, the MT32-PI can also act as a bare metal emulator of the Sound Canvas SC-55.

In this regard, I would like to ask if there is the possibility of making SOFTMPU compatible with games that use DOS/4GW (Doom, Hexen etc.) to fully enjoy this fantastic combo.

Again, thank you so much!

**Comment by bjt42** [comment]
Glad you are enjoying SoftMPU, thanks for your comments.

I believe it's technically possible to capture MIDI streams from protected-mode games. It's a major change that I have no plans to tackle myself, but could be a good candidate for a fork of SOFTMPU by another user.
